import {
  boolean,
  integer,
  json,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

export const jobs = pgTable("jobs", {
  id: uuid("id").primaryKey(),
  title: varchar("title", { length: 40 }),
  employmentModel: text("employment_model"),
  experienceLevel: text("experience_level"),
  description: text("description"),
  jobType: text("job_type"),
  locations: text("locations").array(),
  salaryType: text("salary_type"),
  salaryCurrency: text("salary_currency"),
  salaryRangeFrom: integer("salary_range_from"),
  salaryRangeTo: integer("salary_range_to"),
  applyTarget: text("apply_text"),
  isFeatured: boolean("is_featured").default(false),
  payment: json("payment"),
  isPaymentDone: boolean("is_payment_done").default(false),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
});
